spring:
  profiles:
    active: prod
  #    active: @profiles.active@
  datasource:
    primary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://10.101.167.28:3306/iop?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: aiapp
      password: tFc_99w_
    secondary:
      driver-class-name: com.ibm.db2.jcc.DB2Driver
      jdbcUrl: jdbc:db2://10.101.167.28:50000/BDXDB:currentSchema=FCM;
      username: aiapp
      password: 5bytfAU_

ftp:
  host: 10.109.3.228
  user: vgop_iop
  password: 456vCe!b
  path: /datain/qcd_iop/iop-OOI/sbin-data

file:
  path17: /data1/vgop_iop/iop-OOI/sbin-data